### ISSUE TITLE
youtube

### ISSUE THREAD

**Issue by vbriquet** [CiscoDevNet/roomdevices-macros-samples#12]
Youtube video referenced in README is private, so cannot be seen (https://www.youtube.com/watch?v=7dw9zvvitp8). Thanks !

**Comment by racampos** [comment]
I was about to open an issue about this when I noticed there's one already open. Could you please fix it? It's been 5 months since it was brought to your attention by @vbriquet.

**Comment by dstaudt** [comment]
The link has been updated: https://youtu.be/IQ2Z104Xf50 thanks!
